ignored = [
  "google.golang.org/appengine/urlfetch",
  "github.com/golang/protobuf/proto"
]

[[constraint]]
name = "github.com/bradleyfalzon/ghinstallation"
version = "<1.0.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
