checks:
  golint:
    filters:
    - value: should have comment or be unexported
    - value: or a comment on this block
  errcheck:
    exclude:
      names:
      - ^example$
  compiles:
    exclude:
      names:
      - ^example$
  govet:
    exclude:
      names:
      - ^example$
  ineffassign:
    exclude:
      names:
      - ^example$
  outparamcheck:
    exclude:
      names:
      - ^example$
  unconvert:
    exclude:
      names:
      - ^example$
