products:
  example:
    build:
      output-dir: build
      main-pkg: example
      environment:
        CGO_ENABLED: "0"
      os-archs:
      - os: linux
        arch: amd64
      - os: darwin
        arch: amd64
    dist:
      output-dir: build
      disters:
        os-arch-bin:
          type: os-arch-bin
          config:
            os-archs:
            - os: linux
              arch: amd64
            - os: darwin
              arch: amd64
